version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db
    env_file:
      - ./.env

  redis:
    image: redis:latest
    restart: always